name: C++

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BOOST_ROOT: /usr/local/share/boost/1.72.0

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libjsoncpp-dev uuid-dev

      - name: Run CMake
        run: |
          cmake -S . -B build
          cmake --build build -j 2
