name: C++

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libjsoncpp-dev uuid-dev

      - name: Run CMake
        run: |
          echo "::set-env name=BOOST_ROOT::$BOOST_ROOT_1_72_0"
          cmake -S . -B build -DBoost_INCLUDE_DIRS=$BOOST_ROOT_1_72_0/include
          cmake --build build -j2
